src/Entity/Demandes.php
<?php

namespace App\Entity;

use App\Repository\DemandesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DemandesRepository::class)]
class Demandes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'demandes')]
    private ?User $demandeurs = null;

    #[ORM\ManyToOne(inversedBy: 'demandes')]
    private ?User $artiste = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Message = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $reponse = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDemandeurs(): ?User
    {
        return $this->demandeurs;
    }

    public function setDemandeurs(?User $demandeurs): static
    {
        $this->demandeurs = $demandeurs;

        return $this;
    }

    public function getArtiste(): ?User
    {
        return $this->artiste;
    }

    public function setArtiste(?User $artiste): static
    {
        $this->artiste = $artiste;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): static
    {
        $this->Message = $Message;

        return $this;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(?string $reponse): static
    {
        $this->reponse = $reponse;
        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\EditProfilForm;
use App\Form\DeleteProfilForm;
use App\Form\EditPasswordForm;
use App\Repository\DemandesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

final class ProfilController extends AbstractController
{
    #[Route('/profil/{id}', name: 'app_profil')]
    public function profil( User $user, DemandesRepository $demandes): Response
    {   
        $demande = $demandes->findby(['demandeurs'=> $user]);

        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
            'demandes' => $demande,
            'user' => $user,
            
        ]);
    }
    
    #[Route('/profil/settings/{id}', name: 'app_settings')]
    public function settings(User $user): Response
    {
        return $this->render('profil/settings.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/profil/settings/{id}/edit', name: 'app_profil_change')]
    public function edit(User $user, Request $request, EntityManagerInterface $em,UserPasswordHasherInterface $passwordHasher): Response
    {

        $form = $this->createForm(EditProfilForm::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $form->get('password')->getData();

            if (!$passwordHasher->isPasswordValid($user, $password)) {
            $this->addFlash('erreur', 'L\'ancien mot de passe est incorrect.');
        } else {
            
        $em->flush();
        }

        return $this->redirectToRoute('app_profil', ['id' => $user->getId()]);
    }

        // logique pour modifier les infos
        return $this->render('profil/edit.html.twig', [
            'user' => $user,
            'form' => $form
        ]);
    }

#[Route('/profil/settings/{id}/password', name: 'app_password_change')]
public function changePassword(User $user,Request $request,EntityManagerInterface $em,UserPasswordHasherInterface $passwordHasher): Response {
    $form = $this->createForm(EditPasswordForm::class, $user);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $oldpassword = $form->get('oldpassword')->getData();
        $newpassword = $form->get('newpassword')->getData();

        if (!$passwordHasher->isPasswordValid($user, $oldpassword)) {
            $this->addFlash('erreur', 'L\'ancien mot de passe est incorrect.');
        } else {
            $hashedPassword = $passwordHasher->hashPassword($user, $newpassword);
            $user->setPassword($hashedPassword);

            $em->flush();

            $this->addFlash('success', 'Mot de passe mis à jour avec succès.');
            return $this->redirectToRoute('app_profil', ['id' => $user->getId()]);
        }
    }

    return $this->render('profil/password.html.twig', [
        'user' => $user,
        'form' => $form->createView(),
    ]);
}


#[Route('/profil/settings/{id}/delete', name: 'app_delete_profil')]
public function delete(User $user, EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher,TokenStorageInterface $tokenStorage,RequestStack $requestStack): Response
{
    $form = $this->createForm(DeleteProfilForm::class);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $oldpassword = $form->get('oldpassword')->getData();

        if (!$passwordHasher->isPasswordValid($user, $oldpassword)) {
            $this->addFlash('erreur', 'L\'ancien mot de passe est incorrect.');
        } else {

            $tokenStorage->setToken(null);
            $requestStack->getSession()->invalidate();

            $em->remove($user);
            $em->flush();
            $this->addFlash('success', 'Votre compte a bien été supprimé.');
            return $this->redirectToRoute('app_index');
        }
    }

    return $this->render('profil/delete_profil.html.twig', [
        'deleteForm' => $form->createView(),
        'user' => $user,
        'form' => $form
    ]);
}



}

templates/profil/delete_profil.html.twig
{% extends "base.html.twig" %}

{% block body %}

<h1 class="text-light">Suppression du compte {{ user.username }}</h1>

<a href="{{ path('app_settings', {'id': user.id} )}}" class="btn btn-warning mt-2">Retour</a>

{{form_start(form)}}
<div class="bg-light text-dark container p-2 mt-3">
<p class="mb-2">vous etes sur le point de supprimer votre compte, vous confirmer ?</p>
        {{ form_label(form.oldpassword) }}
        {{ form_widget(form.oldpassword) }}
        {{ form_errors(form.oldpassword) }}
<button class="btn btn-warning mt-2">Supprimer</button>
</div>
{{form_end(form)}}
{% endblock %}

templates/profil/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}

<h1 class="text-light">Modifier vos Information {{user.username}}</h1>

<a href="{{ path('app_settings', {'id': user.id} )}}" class="btn btn-warning">Retour</a>

{{ form_start(form) }}
    <div class="mb-3">
        <label class="text-light">{{ form_label(form.email) }}</label>
        {{ form_widget(form.email) }}
        {{ form_errors(form.email) }}
    </div>

    <div class="mb-3">
        <label class="text-light">{{ form_label(form.username) }}</label>
        {{ form_widget(form.username) }}
        {{ form_errors(form.username) }}
    </div>

    <div class="mb-3">
        <label class="text-light">{{ form_label(form.password)}}</label>
        {{ form_widget(form.password)}}
        {{ form_errors(form.password)}}
    </div>

    <button class="btn btn-primary">Modifier</button>
    
{{ form_end(form) }}

{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block stylesheets %}
    {{ parent() }}
        <link rel="stylesheet" href="{{ asset('styles/profil.css') }}">
{% endblock %}

{% block body %}

    <div class="py-2 bg-light">
    <h1 class="m-3">Bonjour {{user.username}}</h1>
        <h1>vos demandes effectuer</h1>
        {% for demande in demandes %}
            <div class="card text-start">
                <div class="card-body">
                    <h4 class="card-title">{{demande.artiste}}</h4>
                    <p class="card-text">{{demande.message}}</p>
                {% if demande.reponse is not empty %}
                    <img class="warning" src="{{ asset('uploads/alerte.png')}}" alt="reponse !">
                {% endif %}
                </div>

                
                <a href=""><button>consulté</button></a>
            </div>
            
        {% endfor %}
        </section>
    </div>
{% endblock %}

templates/profil/password.html.twig
{% extends "base.html.twig" %}

{% block body %}
<h1 class="text-light">Changement de mot de passe</h1>

<a href="{{ path('app_settings', {'id': user.id} )}}" class="btn btn-warning">Retour</a>

{{ form_start(form) }}

    <div class="mb-3">
        <label class="text-light">{{ form_label(form.oldpassword) }}</label>
        {{ form_widget(form.oldpassword) }}
        {{ form_errors(form.oldpassword) }}
    </div>

    <div class="mb-3">
        <label class="text-light">{{ form_label(form.newpassword) }}</label>
        {{ form_widget(form.newpassword) }}
        {{ form_errors(form.newpassword) }}
    </div>
        <button class="btn btn-primary">Modifier</button>
{{ form_end(form)}}
{% endblock %}

templates/profil/settings.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paramètres de Profile{% endblock %}

{% block body %}

<h2 class="text-light">Paramètres du profil de {{ user.username }}</h2>
{% if is_granted('ROLE_ARTISTE') %}
<a href="{{ path('app_artiste_page', {'id': user.id})}}"><button class="btn btn-warning mt-2">Retour</button></a>
{% else %}
<a href="{{ path('app_profil', {'id': user.id})}}"><button class="btn btn-warning mt-2">Retour</button></a>

{% endif %}



<ul class="bg-light p-5 list-unstyled">
    <li><a href="{{ path('app_profil_change', {'id': user.id}) }}" class="text-dark text-decoration-none">Modifier le profil</a></li>
    <li><a href="{{ path('app_password_change', {'id': user.id}) }}" class="text-dark text-decoration-none">Changer le mot de passe</a></li>
    <li><a href="{{ path('app_delete_profil', { id: app.user.id }) }}" class="text-dark text-decoration-none">Supprimer son compte</a></li>
</ul>

{% endblock %}